release-common-requirements:
  stage: semantic-release
  image: alpine:3.11.5
  variables:
    TAGS_VERSION: 1.0.0
    COMPONENT_TAGS_PROJECT_ID: "intelygenz/science-toolkit"
  script:
    - apk add curl jq bash gettext git coreutils --update
    - wget -q https://github.com/guumaster/monorepo-components-tags/releases/download/v${TAGS_VERSION}/monorepo-components-tags_${TAGS_VERSION}_linux_64-bit.tar.gz -O - | tar -xzO  monorepo-components-tags >  /usr/local/bin/monorepo-components-tags
    - chmod +x /usr/local/bin/monorepo-components-tags
    - /usr/local/bin/monorepo-components-tags --project $COMPONENT_TAGS_PROJECT_ID --commit $CI_COMMIT_SHA --export-shell --suffix TAG --provider GITHUB | tee -a /tmp/components_tags.sh
    - source /tmp/components_tags.sh
    - export JUPYTERLAB_GPU_IMAGE_TAG=$(./scripts/bump-version.sh user-tools-operator-v$JUPYTERLAB_GPU_IMAGE_TAG)
    - export VSCODE_TAG=$(./scripts/bump-version.sh user-tools-operator-v$VSCODE_TAG)
    - export RUNNER_IMAGE_TAG=$(./scripts/bump-version.sh user-tools-operator-v$RUNNER_IMAGE_TAG)
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git remote add upstream https://${GITHUB_PUBLISH_USERNAME}:${GITHUB_PUBLISH_TOKEN}@github.com/intelygenz/science-toolkit.git
    - git tag $JUPYTERLAB_GPU_IMAGE_TAG || true
    - git push upstream $JUPYTERLAB_GPU_IMAGE_TAG || true
    - git tag $VSCODE_TAG || true
    - git push upstream $VSCODE_TAG || true
    - git tag $RUNNER_IMAGE_TAG || true
    - git push upstream $RUNNER_IMAGE_TAG || true
  only:
    changes:
      - common-science-requirements/**/*
    refs:
      - master