apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: autologin
  annotations:
    kubernetes.io/ingress.class: "nginx"

spec:
  rules:
    - host: app.{{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: autologin
              servicePort: http
