trivy-gitea-oauth2-setup:
  extends: .trivy-template
  variables:
    IMAGE_PROJECT_NAME: "terminus7/gitea-oauth2-setup"
    PROJECT_PATH: "gitea-oauth2-setup"
  only:
    refs:
      - master
    changes:
      - gitea-oauth2-setup/**/*

release-gitea-oauth2-setup:
  stage: semantic-release
  image: node:12
  before_script:
    - npm install --prefix gitea-oauth2-setup
  script:
    - cd gitea-oauth2-setup && npx semantic-release -e semantic-release-monorepo
  only:
    refs:
      - master
    changes:
      - gitea-oauth2-setup/**/*

publish-gitea-oauth2-setup-image:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_PROJECT_NAME: "terminus7/gitea-oauth2-setup"
    README_FILEPATH: "./gitea-oauth2-setup/README.md"
  before_script:
    - apk add curl jq bash git coreutils --update
    - TAG=${CI_COMMIT_TAG#"gitea-oauth2-setup-v"}
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t $IMAGE_PROJECT_NAME:$TAG ./gitea-oauth2-setup
    - docker tag $IMAGE_PROJECT_NAME:$TAG $IMAGE_PROJECT_NAME:latest
    - docker push $IMAGE_PROJECT_NAME:$TAG
    - docker push $IMAGE_PROJECT_NAME:latest
    - ./scripts/update-dockerhub-readme.sh
  after_script:
    - docker rmi $IMAGE_PROJECT_NAME:$TAG
  only:
    - /^gitea-oauth2-setup-v\d*.\d*.\d*$/
